"""rag.py — Retrieval-Augmented Generation pipeline.

Given a user query, this module:
  1. Classifies intent
  2. Routes to the right handler (spec lookup / comparison / recommendation / general)
  3. Retrieves relevant products from ChromaDB
  4. Calls the LLM with a carefully-grounded prompt
  5. Returns a structured answer with citations
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterator

import chromadb
from chromadb.utils import embedding_functions

from intent import Intent, IntentResult, classify
from llm import LLM, get_llm


PROJECT_ROOT = Path(__file__).parent.parent
CATALOGUE_JSON = PROJECT_ROOT / "data" / "catalogue.json"
CHROMA_DIR = PROJECT_ROOT / "data" / "chroma_db"

# Public-facing company info.
# These are the ONLY authoritative values for contact details - never let
# the LLM paraphrase or generate them, as a wrong phone number or address
# in front of a real buyer is a serious business error.
CATALOGUE_URL = "https://www.leadpetroleum.com/assets/Catalogue.pdf"
COMPANY_WEBSITE = "https://www.leadpetroleum.com"
COMPANY_EMAIL_GENERAL = "info@leadpetroleum.com"
COMPANY_EMAIL_SUPPORT = "support@leadpetroleum.com"
COMPANY_PHONE = "+971 (55) 575 7330"
COMPANY_ADDRESS = (
    "G-4 Al Bahar 4, Sheikh Ammar Road, Ajman, United Arab Emirates"
)
COMPANY_HOURS = "Mon-Fri, 8:00am - 6:00pm (Gulf Standard Time, UAE)"
COMPANY_SOCIALS = {
    "Facebook": "https://web.facebook.com/leadpetroleum",
    "LinkedIn": "https://pk.linkedin.com/company/lead-petroleum",
    "Instagram": "https://www.instagram.com/lead.petroleum/",
    "X (Twitter)": "https://x.com/leadpetroleum",
}


def catalogue_footer() -> str:
    """Small footer inviting the user to view the full online catalogue."""
    return f"\n\n📄 Full catalogue: {CATALOGUE_URL}"


def contact_block() -> str:
    """Full contact block - used by the 'how do I contact you' canned
    response. Static text, not paraphrased, never generated by the LLM."""
    socials_lines = "\n".join(
        f"  • {name}: {url}" for name, url in COMPANY_SOCIALS.items()
    )
    return (
        f"**Contact Lead Petroleum:**\n\n"
        f"📞 Phone: {COMPANY_PHONE}\n"
        f"✉️  General enquiries: {COMPANY_EMAIL_GENERAL}\n"
        f"✉️  Support: {COMPANY_EMAIL_SUPPORT}\n"
        f"🏢 Address: {COMPANY_ADDRESS}\n"
        f"🕒 Working hours: {COMPANY_HOURS}\n"
        f"🌐 Website: {COMPANY_WEBSITE}\n\n"
        f"**Social media:**\n{socials_lines}"
    )


@dataclass
class Citation:
    product_name: str
    page_ref: int


@dataclass
class Answer:
    text: str
    intent: Intent
    citations: list[Citation] = field(default_factory=list)
    confidence: float = 1.0
    products_used: list[dict] = field(default_factory=list)


# System prompts
SYSTEM_BASE = """\
You are a professional product assistant for Lead Petroleum, a petroleum \
lubricants company. You help buyers find and understand lubricant products.

STRICT RULES (you must follow ALL of these):

1. GROUNDING. Answer ONLY using product information in the CONTEXT below. \
Never invent products, specifications, features, or certifications that are \
not stated in the CONTEXT.

2. CATEGORY MATCHING. Every product in the CONTEXT has a Category field. \
NEVER recommend a product whose category does not match what the user asked \
for. In particular:
   - If the user describes a CAR, sedan, or passenger vehicle, NEVER \
recommend products from "Motorcycle Oil" category (these have "4T" or "2T" \
in the name) or from "Diesel Engine Oil" category.
   - If the user describes a MOTORCYCLE or bike, NEVER recommend "Petrol \
Engine Oil" or "Diesel Engine Oil" category products.
   - If the user describes a TRUCK, bus, or heavy-duty vehicle, NEVER \
recommend "Petrol Engine Oil" or "Motorcycle Oil" products.

3. EXACT NUMERIC SPECS. For viscosity values, pour point, flash point, \
density, TBN, and similar numeric specs: if the exact number is NOT in the \
CONTEXT, do not guess. Say "please check the catalogue page for the exact \
value" and cite the page number.

4. CERTIFICATIONS. Only list certifications that appear verbatim in the \
CONTEXT for the specific product(s) being discussed. NEVER aggregate \
certifications across multiple products as if they are company-wide. \
ASTM D-numbers (D445, D1298, etc.) are test methods, NOT certifications — \
never list them as certifications.

5. CITATIONS. Always end your answer with: [Source: PRODUCT_NAME, page N]. \
If multiple products are cited, list each one.

6. BREVITY. Be concise and professional. A buyer wants a clear, correct \
answer, not a long essay.

7. UNCERTAINTY. If the CONTEXT does not contain enough information, say so \
honestly: "I don't have that information in the catalogue — please check \
the product page."
"""

SYSTEM_COMPARE = SYSTEM_BASE + """\

The buyer is comparing multiple products. Present a clear side-by-side \
comparison highlighting REAL differences in application, performance levels, \
and certifications — only differences stated in the CONTEXT. Do not invent \
differences for the sake of having differences to list.
"""

SYSTEM_RECOMMEND = SYSTEM_BASE + """\

The buyer wants a product recommendation.

Before recommending anything:
- Check the Category field of each product in the CONTEXT.
- Make sure the category matches the buyer's vehicle/application.
- If no product in the CONTEXT matches the correct category, say "I don't \
have a suitable product in the catalogue for this application" rather than \
recommending the wrong category.

API SPEC MODERNITY (CRITICAL):
- If the buyer mentions a recent model year (2010 or later) for a petrol \
car, recommend products labelled [MODERN] or [CURRENT GENERATION] (API SN, \
SP, or higher). NEVER recommend [OBSOLETE] products (API SF/SG/SH) for a \
modern car - these specs are from the 1980s-90s and can cause engine wear.
- For diesel engines 2010 or later, prefer API CJ-4 or CK-4 products.
- If the only products available in the correct category are OBSOLETE, say \
so honestly rather than recommending an unsuitable one.

Pick the best-matching product(s) and explain briefly why it fits (API \
rating, intended application, viscosity range). If more than one product \
fits, rank them with the MOST MODERN spec first.
"""


# ─── Retrieval ───────────────────────────────────────────────────────────────
class Retriever:
    def __init__(self) -> None:
        self._client = chromadb.PersistentClient(path=str(CHROMA_DIR))
        self._collection = self._client.get_or_create_collection(
            name="products",
            embedding_function=embedding_functions.DefaultEmbeddingFunction(),
            metadata={"hnsw:space": "cosine"},
        )
        # Load full product records (metadata in Chroma is limited)
        if CATALOGUE_JSON.exists():
            self._catalogue = {
                p["id"]: p for p in json.loads(CATALOGUE_JSON.read_text())
            }
        else:
            self._catalogue = {}

    def search(
        self, query: str, k: int = 5, category: str | None = None
    ) -> list[dict]:
        """Return the top-k products matching the query, with full records."""
        where = {"category": category} if category else None
        results = self._collection.query(
            query_texts=[query], n_results=k, where=where
        )

        hits: list[dict] = []
        ids = results.get("ids", [[]])[0]
        distances = results.get("distances", [[]])[0]
        for pid, dist in zip(ids, distances):
            product = self._catalogue.get(pid)
            if product:
                hits.append(
                    {
                        **product,
                        "similarity": 1 - dist,  # cosine distance → similarity
                    }
                )
        return hits

    def get_by_name_fragment(self, fragment: str) -> list[dict]:
        """Look up product(s) by a name fragment (e.g. 'yotta 15000')."""
        fragment_l = fragment.lower().strip()
        out = []
        for p in self._catalogue.values():
            if fragment_l in p["name"].lower():
                out.append(p)
        return out

    def all_products(self) -> list[dict]:
        return list(self._catalogue.values())


# API specification modernity ranking.
# Higher = more recent / more modern. Used to help the LLM pick correctly
# when a user mentions a recent model year. API specs are backwards-compatible:
# a 2018 car needs at minimum API SN, and ideally SP.
API_MODERNITY: dict[str, int] = {
    # Petrol / gasoline engine specs (S-series)
    "SA": 1, "SB": 2, "SC": 3, "SD": 4, "SE": 5, "SF": 6, "SG": 7,
    "SH": 8, "SJ": 9, "SL": 10, "SM": 11, "SN": 12, "SP": 13, "SQ": 14,
    # Diesel engine specs (C-series)
    "CA": 1, "CB": 2, "CC": 3, "CD": 4, "CE": 5, "CF": 6,
    "CF-4": 7, "CG-4": 8, "CH-4": 9, "CI-4": 10, "CJ-4": 11, "CK-4": 12,
}

PETROL_MIN_SPEC_FOR_YEAR: list[tuple[int, str]] = [
    (2020, "SP"),
    (2011, "SN"),
    (2004, "SM"),
    (2001, "SL"),
    (1996, "SJ"),
]

DIESEL_MIN_SPEC_FOR_YEAR: list[tuple[int, str]] = [
    (2017, "CK-4"),
    (2010, "CJ-4"),
    (2006, "CI-4"),
    (2002, "CH-4"),
]


def api_level_score(api_level: str | None) -> int:
    """Return a modernity score for an API level string.
    Higher = more modern. Returns 0 if no recognizable API spec found.
    Example: 'API SN/CF' -> 12 (takes the highest gasoline spec).
    """
    if not api_level:
        return 0
    import re as _re
    tokens = _re.findall(r"[SC][A-Z](?:-\d+)?", api_level.upper())
    scores = [API_MODERNITY.get(t, 0) for t in tokens]
    return max(scores) if scores else 0


# Context formatting
def format_product_context(p: dict) -> str:
    """Format a product record for inclusion in the LLM prompt."""
    lines = [f"=== {p['name']} (Catalogue page {p['page_ref']}) ==="]
    lines.append(f"Category: {p['category']}")
    if p.get("viscosity_grades"):
        lines.append(f"Viscosity grades: {', '.join(p['viscosity_grades'])}")
    if p.get("api_level"):
        score = api_level_score(p.get("api_level"))
        modernity_label = ""
        if score >= 12:
            modernity_label = " [MODERN - suitable for recent model years]"
        elif score >= 10:
            modernity_label = " [CURRENT GENERATION - suitable for 2010s+ vehicles]"
        elif score >= 7:
            modernity_label = " [OLDER - suitable for pre-2005 vehicles]"
        elif score > 0:
            modernity_label = " [OBSOLETE - suitable only for very old vehicles, pre-1996]"
        lines.append(f"API level: {p['api_level']}{modernity_label}")
    if p.get("certifications"):
        lines.append(f"Certifications: {', '.join(p['certifications'])}")
    if p.get("description"):
        lines.append(f"Description: {p['description']}")
    if p.get("application"):
        lines.append(f"Application: {p['application']}")
    if p.get("performance_levels"):
        lines.append(f"Performance levels: {p['performance_levels']}")
    # Exact specs if manually curated
    grades = (p.get("specs") or {}).get("grades") or []
    if grades:
        lines.append("Verified typical properties:")
        for g in grades:
            lines.append(f"  - {json.dumps(g, ensure_ascii=False)}")
    return "\n".join(lines)


# ─── RAG engine ──────────────────────────────────────────────────────────────
class RAGEngine:
    def __init__(self, retriever: Retriever | None = None, llm: LLM | None = None):
        self.retriever = retriever or Retriever()
        self.llm = llm or get_llm()

    # ------- public: sync answer -------
    def answer(self, query: str) -> Answer:
        # Short-circuit for generic company-wide questions that the LLM is
        # prone to fabricating answers for. We detect these and return a
        # deterministic response that redirects the user to a productive
        # per-product query.
        canned = self._canned_company_response(query)
        if canned:
            return canned

        result = classify(query)

        if result.intent == Intent.EXACT_SPEC:
            return self._answer_exact_spec(query, result)
        if result.intent == Intent.COMPARE:
            return self._answer_compare(query, result)
        if result.intent == Intent.RECOMMEND:
            return self._answer_recommend(query, result)
        return self._answer_general(query, result)

    # ------- public: streaming answer -------
    def stream(self, query: str) -> Iterator[str]:
        # Canned responses for generic company questions - stream verbatim
        canned = self._canned_company_response(query)
        if canned:
            yield canned.text
            return

        result = classify(query)

        if result.intent == Intent.EXACT_SPEC:
            # Exact spec queries: try to answer from structured data first
            # (no LLM), to avoid hallucinated numbers entirely.
            products = self._resolve_products(result.products_mentioned)
            if products:
                spec_answer = self._structured_spec_answer(products[0], result.spec_mentioned)
                if spec_answer:
                    yield spec_answer
                    return
            # fall through to general RAG if no structured answer
            result = IntentResult(Intent.GENERAL, result.products_mentioned, result.spec_mentioned)

        products = self._retrieve_for_intent(query, result)
        system = self._system_for_intent(result.intent)
        context = "\n\n".join(format_product_context(p) for p in products)
        prompt = f"CONTEXT:\n{context}\n\nUSER QUESTION: {query}\n\nAnswer:"

        yield from self.llm.stream(system=system, user=prompt, temperature=0.0)

        # Append the catalogue URL after the LLM response so users can
        # verify specs in the source PDF. Only do this when we actually
        # retrieved products (otherwise no relevant source to point to).
        if products:
            yield catalogue_footer()

    # ------- handlers -------
    def _answer_exact_spec(self, query: str, result: IntentResult) -> Answer:
        products = self._resolve_products(result.products_mentioned)
        if products:
            spec_answer = self._structured_spec_answer(
                products[0], result.spec_mentioned
            )
            if spec_answer:
                return Answer(
                    text=spec_answer,
                    intent=Intent.EXACT_SPEC,
                    citations=[
                        Citation(products[0]["name"], products[0]["page_ref"])
                    ],
                    confidence=1.0,
                    products_used=products[:1],
                )
        # No structured answer → delegate to general RAG with stern prompt
        return self._answer_general(query, result)

    def _answer_compare(self, query: str, result: IntentResult) -> Answer:
        products = self._retrieve_for_intent(query, result)
        system = SYSTEM_COMPARE
        context = "\n\n".join(format_product_context(p) for p in products)
        prompt = f"CONTEXT:\n{context}\n\nUSER QUESTION: {query}\n\nAnswer:"
        text = self.llm.generate(system=system, user=prompt, temperature=0.0)
        if products:
            text += catalogue_footer()
        return Answer(
            text=text,
            intent=Intent.COMPARE,
            citations=[Citation(p["name"], p["page_ref"]) for p in products],
            confidence=min((p.get("similarity") or 1.0) for p in products) if products else 0.0,
            products_used=products,
        )

    def _answer_recommend(self, query: str, result: IntentResult) -> Answer:
        products = self._retrieve_for_intent(query, result)
        system = SYSTEM_RECOMMEND
        context = "\n\n".join(format_product_context(p) for p in products)
        prompt = f"CONTEXT:\n{context}\n\nUSER QUESTION: {query}\n\nAnswer:"
        text = self.llm.generate(system=system, user=prompt, temperature=0.0)
        if products:
            text += catalogue_footer()
        return Answer(
            text=text,
            intent=Intent.RECOMMEND,
            citations=[Citation(p["name"], p["page_ref"]) for p in products[:3]],
            confidence=products[0].get("similarity", 0.0) if products else 0.0,
            products_used=products[:3],
        )

    def _answer_general(self, query: str, result: IntentResult) -> Answer:
        products = self._retrieve_for_intent(query, result)
        system = SYSTEM_BASE
        context = "\n\n".join(format_product_context(p) for p in products)
        prompt = f"CONTEXT:\n{context}\n\nUSER QUESTION: {query}\n\nAnswer:"
        text = self.llm.generate(system=system, user=prompt, temperature=0.0)
        if products:
            text += catalogue_footer()
        return Answer(
            text=text,
            intent=result.intent,
            citations=[Citation(p["name"], p["page_ref"]) for p in products[:3]],
            confidence=products[0].get("similarity", 0.0) if products else 0.0,
            products_used=products[:3],
        )

    # ------- helpers -------
    def _resolve_products(self, mentions: list[str]) -> list[dict]:
        found: list[dict] = []
        for m in mentions:
            for p in self.retriever.get_by_name_fragment(m):
                if p not in found:
                    found.append(p)
        return found

    def _retrieve_for_intent(
        self, query: str, result: IntentResult
    ) -> list[dict]:
        # If specific products are mentioned, fetch them directly first
        direct = self._resolve_products(result.products_mentioned)
        if direct and result.intent == Intent.COMPARE:
            return direct  # comparison — only return the named products

        # If we inferred a category from the query (e.g. "Mehran" -> Petrol
        # Engine Oil), filter retrieval to that category only. This prevents
        # semantic search from matching the wrong product category just
        # because it shares some words.
        category_filter = result.inferred_category

        # Otherwise semantic search
        k = 5 if result.intent == Intent.RECOMMEND else 5
        semantic = self.retriever.search(query, k=k, category=category_filter)

        # If the category filter returned nothing, fall back to unfiltered
        # search so the user still gets an answer (the LLM prompt will still
        # refuse to recommend across categories).
        if category_filter and not semantic:
            semantic = self.retriever.search(query, k=k)

        # Merge direct mentions first, then semantic
        seen = {p["id"] for p in direct}
        for p in semantic:
            if p["id"] not in seen:
                direct.append(p)
                seen.add(p["id"])
        return direct[:k]

    def _canned_company_response(self, query: str) -> Answer | None:
        """Detect generic company-wide questions and return a deterministic
        response instead of letting the LLM fabricate one.

        Small LLMs tend to hallucinate on questions like "what certifications
        does Lead Petroleum hold" because they try to produce a complete-looking
        list and draw on training-data knowledge of other brands. Our honest
        answer is: certifications are per-product - tell me which product.

        Returns None if the query is not a generic company-wide question, so
        normal RAG routing takes over.
        """
        q = query.lower().strip()

        # Company-wide certification / standards questions without a specific
        # product mentioned.
        from intent import find_products

        company_cert_patterns = [
            r"\bwhat certifications?\b",
            r"\bwhich certifications?\b",
            r"\blist.+certifications?\b",
            r"\ball certifications?\b",
            r"\bcertifications? (do you|does lead|does the company)\b",
            r"\bapprovals? (do you|does lead|does the company)\b",
            r"\bstandards? (do you|does lead|does the company)\b",
            r"\bwhat (standards?|approvals?) (do|does)\b",
            r"\b(company|lead petroleum) (certifications?|approvals?|standards?)\b",
        ]
        if any(re.search(p, q) for p in company_cert_patterns):
            # Only trigger if NO specific product was mentioned
            if not find_products(query):
                text = (
                    "Certifications and approvals vary by product, so I can "
                    "share them most accurately for a specific one. Which "
                    "product are you interested in?\n\n"
                    "For example, you could ask:\n"
                    "  - What certifications does LEAD YOTTA 15000 have?\n"
                    "  - What API rating does LEAD ZETTA 15000 meet?\n"
                    "  - What ACEA standards does LEAD MEGA 7000 comply with?\n\n"
                    "Or you can ask about a specific application (e.g. "
                    "\"API CK-4 diesel oils\") and I'll show the matching "
                    "products with their certifications."
                )
                return Answer(
                    text=text,
                    intent=Intent.GENERAL,
                    citations=[],
                    confidence=1.0,
                    products_used=[],
                )

        # Generic "tell me about Lead Petroleum" / "what is Lead Petroleum"
        about_patterns = [
            r"^\s*what is lead petroleum\s*\??\s*$",
            r"^\s*tell me about lead petroleum\s*\??\s*$",
            r"^\s*about lead petroleum\s*\??\s*$",
            r"^\s*who is lead petroleum\s*\??\s*$",
        ]
        if any(re.search(p, q) for p in about_patterns):
            text = (
                "Lead Petroleum is a manufacturer of automotive and industrial "
                "lubricants, greases, and specialty products, based in Ajman, "
                "United Arab Emirates. Our catalogue includes 48 products "
                "across categories spanning petrol and diesel engine oils, "
                "motorcycle oils, ATF and gear oils, coolants, brake fluids, "
                "greases, hydraulic oils, marine oils, and industrial "
                "lubricants.\n\n"
                "What would you like to know? I can help with:\n"
                "  • Product recommendations for a specific vehicle or application\n"
                "  • Product comparisons\n"
                "  • Certifications and performance levels for a specific product\n"
                "  • Browsing products in a particular category\n"
                "  • Contact details (ask \"how can I contact you?\")"
            )
            return Answer(
                text=text,
                intent=Intent.GENERAL,
                citations=[],
                confidence=1.0,
                products_used=[],
            )

        # Contact / location / hours / phone / email questions.
        # Never let the LLM handle these - we serve the authoritative
        # contact block directly to avoid any chance of a wrong number
        # or address.
        contact_patterns = [
            r"\b(how (can|do) i )?contact\b",
            r"\b(what is|what's|whats) your (phone|email|number|address)\b",
            r"\b(phone|telephone) number\b",
            r"\bemail address\b",
            r"\b(where are you|where is lead petroleum) (based|located)\b",
            r"\bwhere (can i|do i|to) (find|reach|call)\b",
            r"\b(office |company )?(address|location)\b",
            r"\b(working|office|business) hours\b",
            r"\bopening (hours|times)\b",
            r"\bwhen are you open\b",
            r"\bcan i (speak|talk) to (a )?human\b",
            r"\b(customer )?support\b(?! for)",
            r"\bhow (do i|to) reach\b",
            r"\bsocial media\b",
            r"\b(facebook|linkedin|instagram|twitter)\b",
        ]
        if any(re.search(p, q) for p in contact_patterns):
            return Answer(
                text=contact_block(),
                intent=Intent.GENERAL,
                citations=[],
                confidence=1.0,
                products_used=[],
            )

        return None

    def _system_for_intent(self, intent: Intent) -> str:
        if intent == Intent.COMPARE:
            return SYSTEM_COMPARE
        if intent == Intent.RECOMMEND:
            return SYSTEM_RECOMMEND
        return SYSTEM_BASE

    def _structured_spec_answer(
        self, product: dict, spec: str | None
    ) -> str | None:
        """Return a direct answer from manual specs CSV, or None if not available."""
        grades = (product.get("specs") or {}).get("grades") or []
        name = product["name"]
        page = product["page_ref"]

        if not spec:
            return None

        if not grades:
            return (
                f"The {spec.replace('_', ' ')} for {name} is not in our "
                f"structured data yet. Please refer to catalogue page {page} "
                f"for the exact value. "
                f"[Source: {name}, page {page}]"
                f"{catalogue_footer()}"
            )

        # Try to pull the value from the grades rows
        values = []
        for g in grades:
            for k, v in g.items():
                if spec in k or k in spec:
                    values.append(f"{g.get('viscosity_grade', '')}: {v}".strip(": "))

        if not values:
            return (
                f"The {spec.replace('_', ' ')} for {name} is not in our "
                f"structured data yet. Please refer to catalogue page {page}. "
                f"[Source: {name}, page {page}]"
                f"{catalogue_footer()}"
            )

        return (
            f"{name} — {spec.replace('_', ' ')}:\n"
            + "\n".join(f"  • {v}" for v in values)
            + f"\n\n[Source: {name}, page {page}]"
            + catalogue_footer()
        )
